### PR TITLE
all thumbnail attributes on about pages

### PR DESCRIPTION
**Pull request by starsplatter**

### CODE REVIEW

**Comment by starsplatter** [comment]
I suspect this was oversight rather than a decision because the front end for creating the thumbnails is already there (which is why Karl was able to try and do it). The thumbnail behavior got halfway moved on to the about_pages but not completely. I asked on the main project though to be sure and the response seemed positive. https://github.com/projectblacklight/spotlight/issues/1806

**Comment by cappadona** [comment]
Thanks, Jenn. Didn't realize you had added an issue in the spotlight repo. That's great and FWIW, I agree that the PR should update the `Spotlight::Page` model since all of the other page types inherit from it.

**Comment by ggeisler** [comment]
@starsplatter Did this PR get About page thumbnails working for you? 

I noticed that in our Stanford exhibits I still can't create thumbnails. I then tried in the latest Spotlight locally and it also doesn't work. 

I don't see any error when trying to use an exhibit item as the image source (the flash message says it was saved but returning to the Thumbnail tab shows it is empty). When using a local image as an image source I see the same behavior but also see the following in the console, which seems like it might be related:

```
Can't verify CSRF token authenticity.
Completed 401 Unauthorized in 2ms (ActiveRecord: 0.0ms)

ActionController::InvalidAuthenticityToken (ActionController::InvalidAuthenticityToken):
```

**Comment by elrayle** [comment]
NOTE: Added to Spotlight code in https://github.com/projectblacklight/spotlight/pull/2027/files

**Pull request merged**
